import Head from 'next/head'
import Image from 'next/image'

import hero from './assets/images/hero.png'
import arrowRight from '../pages/assets/icons/arrowRight.svg'
import step2 from './assets/icons/step2.svg'

import congratulations from './assets/icons/congrats.svg'
import stick from './assets/icons/stick.svg'
import userStatusBar from './assets/icons/userStatusBar.svg'
import FormStep2 from './components/formStep2'
import FormStep1 from './components/formStep1'
import { useState } from 'react'
import ButtonStep from './components/buttonStep'

export default function Home() {
  const [formStep, setFormStep] = useState(0);
  const formTitle = ['Preencha o Formulário', 'Preencha o Formulário', 'Parabéns']
  return (
    <>
      <Head>
        <title>Grupo W</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex flex-col bg-hero bg-cover bg-no-repeat w-screen h-screen justify-center items-center'>
        <section id='form' className='flex flex-col h-screen justify-between'>
          <div className="flex flex-col w-full justify-end h-full items-center text-center mb-6">
            <div className="flex px-8">
              <Image src={hero} alt="Logomarca principal do grupo w" />
            </div>

            <div className="flex px-10">
              <p className='text-primary-default opacity-60 text-sm font-normal'>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
            </div>
          </div>

          <div className="flex flex-col w-full rounded-lg justify-center gap-5 px-4 py-12 bg-secondary-default">
            <h2 className='text-primary-default opacity-80 text-2xl text-center'>{formTitle[formStep]}</h2>

              {formStep === 0
                &&(
                  <>
                    <div className="flex flex-row justify-start gap-2">
                    <Image src={stick} alt="statusBar" />
                    <Image src={userStatusBar} alt="statusBar progresso 1 de 3" />
                    <Image src={stick} alt="statusBar" />
                    </div>

                    <div className='flex flex-col justify-around gap-5 items-center'>
                      <FormStep1 />

                      <div className="flex flex-row w-11/12 justify-end">
                        <ButtonStep action={() => setFormStep((current) => current + 1)} field='Próximo' />
                      </div>
                    </div>
                  </>
                )
              }
              {formStep === 1
                &&(
                  <>
                    <div className="flex flex-row justify-start gap-2">
                    <Image src={stick} alt="statusBar" />
                    <Image src={userStatusBar} alt="statusBar progresso 1 de 3" />
                    <Image src={stick} alt="statusBar" />
                    <Image src={step2} alt="statusBar progresso 2 de 3" />
                    </div>
                    
                    <div className='flex flex-col justify-around gap-5 items-center px-4'>
                      <FormStep2 />

                      <div className="flex flex-row-reverse w-11/12 justify-between">
                        <ButtonStep action={() => setFormStep((current) => current + 1)} field='Finalizar' />

                        <button onClick={() => setFormStep((current) => current - 1)} className="flex flex-row items-center gap-3">
                          <div className="flex bg-primary-alternative items-center justify-center rounded-full py-2 px-2">
                              <Image className='rotate-180' src={arrowRight} alt="Seta para direita" />
                          </div>
                          
                          <div className="flex">
                              <p className='text-primary-default'>Anterior</p>
                          </div>
                        </button>
                      </div>
                    </div>
                  </>
                )
              }
              {formStep === 2
                &&(
                  <div className='flex flex-col w-full justify-center items-center text-center gap-5 text-center'>
                    <Image src={congratulations} alt="Ilustração de pessoas felizes comemorando" />

                    <p className='text-primary-default text-sm px-6'><span className='font-semibold'>Recebemos seus dados,</span> agora basta aguardar que logo entraremos em contato com você!</p>

                    <button className='flex text-center justify-center px-6 py-4 bgFinalFormButton text-secondary-default'>
                      Entendi
                    </button>

                    <button className='text-primary-default text-xs' onClick={() => setFormStep((current) => current - 1)}>Preencheu algo errado?</button>
                  </div>
                )
              }

          </div>
        </section>
      </main>
    </>
  )
}
